backend:
  name: git-gateway
  branch: main

media_folder: "media"
public_folder: "media"

collections:
  - name: "products"
    label: "Products"
    folder: "_products"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: ["cheese", "cold-cuts", "antipasti", "fish", "sauces", "sweets", "pasta-rice-flour"]}
      - {label: "Subcategory", name: "subcategory", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "ID", name: "id", widget: "string"}
    body: false
