backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "public/uploads/images" # Media files will be stored in the repo under public/uploads/images
public_folder: "/uploads/images" # The src attribute for uploaded media will begin with /uploads/images
collections:
  - name: "products"
    label: "Products"
    folder: "_products"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Image", name: "image", widget: "image"}