[build]
  publish = "."
  command = "echo 'Static site - no build needed'"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

[[redirects]]
  from = "/.netlify/images/*"
  to = "/.netlify/images/:splat"
  status = 200