[build]
  publish = "."
  command = "echo 'Static site - no build needed'"

# Redirect all admin routes to the admin interface
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Enable Git Gateway and Identity for Decap CMS
[context.production]
  environment = { NODE_ENV = "production" }

# Enable Large Media for handling large files
[build.environment]
  NODE_VERSION = "18"
