backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads/images"
public_folder: "/uploads/images"

collections:
  - name: "products"
    label: "Products"
    folder: "_products"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Category", name: "category", widget: "select", options: ["pasta-rice-flour", "cheese-cold-cuts", "seasonal", "coffee-tea", "wine-liquor", "sweets-snacks", "sauces-condiments"]}
      - {label: "Published", name: "published", widget: "boolean", default: true}